### ISSUE TITLE
error in C function hexo-config: Argument should be a string.

### ISSUE THREAD

**Issue by gd4Ark** [mamboer/hexo-renderer-scss#8]
_config.yml:
```yml
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:    
```
_variables.scss:
```scss
$highlight: hexo-config('highlight.enable');
```
Report an error：
```shell
Error: error in C function hexo-config: Argument should be a string.
```

**Comment by aispin** [comment]
hi, can u pls provide a sample project ?

**Comment by gd4Ark** [comment]
I found a less elegant solution:
_config.yml:
```yml
  highlight:
    enable: false
    _enable: "false" # （BUG?）scss can only get a string
```
_variables.scss:
```scss
$highlight: hexo-config('highlight._enable');
```
other scss:
```scss
@if ($highlight !='false') {
 // do something
}
```

If you have a better solution, please let us know.
